const movies = [
  {
    title: 'Homem de Ferro (2008)',
    subtitle: 'Heróis não nascem. Eles são construídos.',
    storyline: 'Tony Stark, ao ser sequestrado é obrigado por terroristas a construir uma arma devastadora mas, ao invés disto, constrói uma armadura de alta tecnologia que permite que fuja de seu cativeiro.',
    rating: 76,
    imagePath: 'https://www.themoviedb.org/t/p/original/s6cQgJSkviamXAXBggT2xmj7JiG.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'O Incrível Hulk (2008)',
    subtitle: 'Nossa única esperança será algo incrível.',
    storyline: 'Vivendo escondido e longe de Betty Ross, a mulher que ama, o cientista Bruce Banner busca um meio de retirar a radiação gama que está em seu sangue.',
    rating: 62,
    imagePath: 'https://www.themoviedb.org/t/p/original/xfBnQ4mgf1jYZsscJGJjr6ce0Ar.jpg',
    bookmarked: false,
    genre: 'action',
  },
  {
    title: 'Homem de Ferro 2 (2010)',
    subtitle: 'Não é a armadura que faz o herói, mas o homem dentro da armadura.',
    storyline: 'Em um mundo ciente da existência do Homem de Ferro, o inventor bilionário Tony Stark sofre pressão de todos os lados para compartilhar sua tecnologia com as forças armadas.',
    rating: 68,
    imagePath: 'https://www.themoviedb.org/t/p/original/hCVQPB77eXBGh9abVdrWtKpKgkN.jpg',
    bookmarked: false,
    genre: 'action',
  },
  {
    title: 'Thor (2011)',
    subtitle: 'A coragem é imortal.',
    storyline: 'Como filho de Odin, rei dos deuses nórdicos, Thor logo herdará o trono de Asgard de seu idoso pai. Porém, no dia de sua coroação, Thor reage com brutalidade quando os inimigos dos deuses entram no palácio violando o tratado.',
    rating: 68,
    imagePath: 'https://www.themoviedb.org/t/p/original/3XyaYiOHldsNhwnXKDRYOpFc1nB.jpg',
    bookmarked: false,
    genre: 'action',
  },
  {
    title: 'Capitão América: O Primeiro Vingador (2011)',
    subtitle: 'Quando patriotas se tornam heróis!',
    storyline: 'Quando os oficiais militares conseguem transformá Steve Rogers em uma arma humana, eles percebem que não podem arriscar a vida do jovem nas batalhas de guerra.',
    rating: 70,
    imagePath: 'https://www.themoviedb.org/t/p/original/yFuKvT4Vm3sKHdFY4eG6I4ldAnn.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Os Vingadores: The Avengers (2012)',
    subtitle: 'Os maiores heróis da terra juntos.',
    storyline: 'Loki, o irmão de Thor, ganha acesso ao poder ilimitado do cubo cósmico ao roubá-lo de dentro das instalações da S.H.I.E.L.D. ',
    rating: 77,
    imagePath: 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/nNmJRkg8wWnRmzQDe2FwKbPIsJV.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Homem de Ferro 3 (2013)',
    subtitle: 'Liberte o poder por trás da armadura.',
    storyline: 'Depois de um inimigo reduzir o mundo de Tony Stark a destroços, o Homem de Ferro precisa aprender a confiar em seus instintos para proteger aqueles que ama, especialmente sua namorada, e lutar contra seu maior medo: o fracasso.',
    rating: 69,
    imagePath: 'https://www.themoviedb.org/t/p/original/4TSqtluelcWByj8YZdqwzQVjI0O.jpg',
    bookmarked: false,
    genre: 'action',
  },
  {
    title: 'Thor: O Mundo Sombrio (2013)',
    subtitle: 'Mergulhe na escuridão',
    storyline: 'Thor precisa contar com a ajuda de seus companheiros e até de seu traiçoeiro irmão Loki em um plano audacioso para salvar o universo. Entretanto, os caminhos de Thor se cruzam com Jane Foster e, dessa vez, a vida dela está realmente em perigo.',
    rating: 66,
    imagePath: 'https://www.themoviedb.org/t/p/original/5QEOy0QEpad9QsXeMxuGHPXMale.jpg',
    bookmarked: false,
    genre: 'action',
  },
  {
    title: 'Capitão América 2: O Soldado Invernal (2014)',
    subtitle: 'Em heróis nós confiamos.',
    storyline: 'Após os eventos catastróficos em Nova York com Os Vingadores, Steve Rogers, segue tentando se ajustar ao mundo moderno. Porém, Steve se vê preso em uma rede de intrigas que ameaça colocar o mundo em risco.',
    rating: 77,
    imagePath: 'https://www.themoviedb.org/t/p/original/55zqM1Dt1kVFOQf0ddgjhS3SCf7.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Guardiões da Galáxia (2014)',
    subtitle: 'Todos os heróis começam em algum lugar.',
    storyline: 'O aventureiro do espaço Peter Quill torna-se presa de caçadores de recompensas depois que rouba a esfera de um vilão traiçoeiro, Ronan. Para escapar do perigo, ele faz uma aliança com um grupo de quatro extraterrestres.',
    rating: 79,
    imagePath: 'https://www.themoviedb.org/t/p/original/oEaSZoAkebncG89u3MF9wXw7H5H.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Vingadores: Era de Ultron (2015)',
    subtitle: 'Começa uma nova era.',
    storyline: 'Ao tentar proteger o planeta de ameaças, Tony Stark constrói um sistema de inteligência artificial que cuidaria da paz mundial. O projeto acaba dando errado e gera o nascimento do Ultron. ',
    rating: 73,
    imagePath: 'https://cinematologia.com.br/cine/wp-content/uploads/2019/04/Capa-3.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Homem-Formiga (2015)',
    subtitle: 'Você nunca viu um herói tão grandioso!',
    storyline: 'Depois de sair da cadeia, o trambiqueiro Scott Lang (Paul Rudd) está disposto a reconquistar o respeito da ex-mulher, Maggie (Judy Greer) e, principalmente, da filha. Com dificuldades de arrumar um emprego honesto, ele aceita praticar um último golpe. ',
    rating: 71,
    imagePath: 'https://www.themoviedb.org/t/p/original/7AyEEZVtFjNMCOEoz88pBqiAI8n.jpg',
    bookmarked: false,
    genre: 'action',
  },
  {
    title: 'Capitão América: Guerra Civil (2016)',
    subtitle: 'Unidos Venceremos. Divididos Cairemos.',
    storyline: 'O ataque de Ultron fez com que os políticos buscassem algum meio de controlar os super-heróis, já que seus atos afetam toda a humanidade. Tal decisão coloca o Capitão América em rota de colisão com Tony Stark, o Homem de Ferro.',
    rating: 74,
    imagePath: 'https://www.themoviedb.org/t/p/original/ilYlW1nJG3jdxSJlsd5pjfVhTLg.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Doutor Estranho (2016)',
    subtitle: 'As impossibilidades são infinitas.',
    storyline: 'Dr. Stephen Strange, cuja vida muda para sempre depois de um terrível acidente de carro, que o rouba do uso de suas mãos. Quando a medicina tradicional o falha, ele é forçado a procurar por cura e esperança, em um lugar improvável - um enclave misterioso conhecido como Kamar-Taj. ',
    rating: 74,
    imagePath: 'https://www.themoviedb.org/t/p/original/eQN31P4IEhyp6NkdccvppJnyuJ4.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Guardiões da Galáxia Vol. 2 (2017)',
    subtitle: 'Obviamente',
    storyline: 'Os Guardiões precisam lutar para manter sua recém descoberta família unida, enquanto descobrem os mistérios sobre o verdadeiro pai de Peter Quill.',
    rating: 76,
    imagePath: 'https://www.themoviedb.org/t/p/original/aJn9XeesqsrSLKcHfHP4u5985hn.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Homem-Aranha: De Volta ao Lar (2017)',
    subtitle: 'O dever de casa pode esperar. A cidade não.',
    storyline: 'Depois de atuar ao lado dos Vingadores, chegou a hora do pequeno Peter Parker (Tom Holland) voltar para casa e para a sua vida, já não mais tão normal. ',
    rating: 74,
    imagePath: 'https://www.themoviedb.org/t/p/original/24GSBmRoQlX7tnHvH5BTPq2eMVQ.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Thor: Ragnarok (2017)',
    subtitle: 'Sem martelo. Sem problemas.',
    storyline: 'Thor está preso do outro lado do universo. Ele precisa correr contra o tempo para voltar a Asgard e parar Ragnarok, a destruição de seu mundo, que está nas mãos da poderosa e implacável vilã Hela.',
    rating: 76,
    imagePath: 'https://www.themoviedb.org/t/p/original/5wNUJs23rT5rTBacNyf5h83AynM.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Pantera Negra (2018)',
    subtitle: 'Os Vingadores têm um novo rei.',
    storyline: 'O príncipe T-Challa retorna a Wakanda para ser coroado rei. Assumindo o manto de Pantera Negra, ele vai à caça de um vilão que roubou um precioso metal de seu país.',
    rating: 74,
    imagePath: 'https://www.themoviedb.org/t/p/original/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Vingadores: Guerra Infinita (2018)',
    subtitle: 'Um universo inteiro. De uma vez por todas.',
    storyline: 'Homem de Ferro, Thor, Hulk e os Vingadores se unem para combater seu inimigo mais poderoso, o maligno Thanos.',
    rating: 83,
    imagePath: 'https://www.themoviedb.org/t/p/original/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Homem-Formiga e a Vespa (2018)',
    subtitle: 'Heróis reais. Tamanho não real.',
    storyline: 'Scott Lang lida com as consequências de suas escolhas tanto como super-herói quanto como pai. ',
    rating: 70,
    imagePath: 'https://www.themoviedb.org/t/p/original/6P3c80EOm7BodndGBUAJHHsHKrp.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Capitã Marvel (2019)',
    subtitle: 'Mais alto. Mais longe. Mais rápido.',
    storyline: 'Capitã Marvel, parte do exército de elite dos Kree, uma raça alienígena, encontra-se no meio de uma batalha entre seu povo e os Skrulls. ',
    rating: 70,
    imagePath: 'https://www.themoviedb.org/t/p/original/qAzYK4YPSWDc7aa4R43LcwRIAyb.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Vingadores: Ultimato (2019)',
    subtitle: 'O fim de uma era!',
    storyline: 'Após os eventos devastadores de "Vingadores: Guerra Infinita", o universo está em ruínas devido aos esforços do Titã Louco, Thanos. ',
    rating: 83,
    imagePath: 'https://www.themoviedb.org/t/p/original/r0jfRKIIKl34kZCeTxInYu5bVPf.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    title: 'Homem-Aranha: Longe de Casa (2019)',
    subtitle: 'Continuar é preciso.',
    storyline: 'Peter Parker está em uma viagem de duas semanas pela Europa, ao lado de seus amigos de colégio, quando é surpreendido pela visita de Nick Fury. ',
    rating: 75,
    imagePath: 'https://www.themoviedb.org/t/p/original/5myQbDzw3l8K9yofUXRJ4UTVgam.jpg',
    bookmarked: true,
    genre: 'action',
  },
];

export default movies;
